# Configuration file used for testing the 'synapse_port_db' script.
# Tells the 'update_database' script to connect to the test SQLite database to upgrade its
# schema and run background updates on it.
server_name: "localhost:8800"

signing_key_path: ".buildkite/test.signing.key"

report_stats: false

database:
  name: "sqlite3"
  args:
    database: ".buildkite/test_db.db"

# Suppress the key server warning.
trusted_key_servers: []
